# Generated by Django 4.2.9 on 2024-02-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Waypoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=3090)),
                ("wp_id", models.CharField(max_length=3090)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
