# Generated by Django 4.2.9 on 2024-02-03 06:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nav", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="waypoint",
            name="active",
        ),
    ]
