# Generated by Django 4.2.9 on 2024-02-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nav", "0003_port_waypoint_port_in_waypoint_port_out"),
    ]

    operations = [
        migrations.AlterField(
            model_name="port",
            name="latitude",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="port",
            name="longitude",
            field=models.FloatField(blank=True),
        ),
    ]
