# Generated by Django 4.2.9 on 2024-02-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nav", "0004_alter_port_latitude_alter_port_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="port",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="port",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
