# Generated by Django 4.2.9 on 2024-02-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nav", "0005_alter_port_latitude_alter_port_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waypoint",
            name="port_in",
            field=models.ManyToManyField(
                blank=True, default=None, related_name="port_in", to="nav.port"
            ),
        ),
        migrations.AlterField(
            model_name="waypoint",
            name="port_out",
            field=models.ManyToManyField(
                blank=True, default=None, related_name="port_out", to="nav.port"
            ),
        ),
    ]
