# Generated by Django 4.2.9 on 2024-02-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nav", "0006_alter_waypoint_port_in_alter_waypoint_port_out"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="port",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="port",
            name="longitude",
        ),
        migrations.AddField(
            model_name="port",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="port",
            name="semantics",
            field=models.CharField(default="", max_length=3090),
        ),
    ]
