# Generated by Django 4.2.9 on 2024-02-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nav", "0007_remove_port_latitude_remove_port_longitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="waypoint",
            name="port_in",
        ),
        migrations.RemoveField(
            model_name="waypoint",
            name="port_out",
        ),
        migrations.AddField(
            model_name="waypoint",
            name="port",
            field=models.ManyToManyField(
                blank=True, default=None, related_name="ports", to="nav.port"
            ),
        ),
    ]
